whitelist_rules: # rule identifiers use for autocorrect
  - trailing_whitespace
  - colon
  - comma
  - vertical_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods