# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'
inhibit_all_warnings!

target 'Spotify' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spotify
  pod 'SwiftLint', '~> 0.30.1'
  pod 'SwiftMessages', '~> 6.0.2'
  pod 'ReachabilitySwift', '~> 4.3.0'
  pod 'SwiftGen', '~> 6.0.2'
end

target 'SpotifyTests' do
   inherit! :search_paths
   # Pods for testing
end

target 'SpotifyUITests' do
  inherit! :search_paths
  # Pods for testing
end

target 'SpotifyCore' do
  use_frameworks!
  
  # Pods for SpotifyCore
  pod 'ReachabilitySwift', '~> 4.3.0'
  pod 'SwiftMessages', '~> 6.0.2'

end

target 'SpotifyUI' do
  use_frameworks!
  
  # Pods for SpotifyUI
  pod 'AlamofireImage', '~> 3.5.0'
  pod 'RxSwift', '~> 4.4.0'
end

post_install do |installer|
    puts 'Add whole module optimization for all Swift pods Debug configuration'
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'Debug'
		config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = "YES"
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
                config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -Onone'

             end
        end
    end
end